### ISSUE TITLE
FineUploader Laravel Example with AWS SDK v3

### ISSUE THREAD

**Issue by n7best** [FineUploader/php-s3-server#1]
This is a Laravel port with AWS SDKv3 if anyone interested.
https://gist.github.com/n7best/6d72092e4628e75f3452

**Comment by rnicholus** [comment]
Is this something you would be willing to contribute directly to the FineUploader org, ideally as a standalone repo?

**Comment by n7best** [comment]
Sure, hope it could save others sometime.

**Comment by rnicholus** [comment]
I'd by happy to create a new repo and add you to the organization to maintain it.

**Comment by n7best** [comment]
Glad I can help. Will do a pr after repo is up. :)

**Comment by rnicholus** [comment]
I just created [a repo](https://github.com/FineUploader/php-laravel-s3-server) and invited you to administer it. Sorry for the late reply to your initial post - I was out of the country in December and this must have slipped under my radar.
