### ISSUE TITLE
Concern about validating requests before signing

### ISSUE THREAD

**Issue by hubgit** [FineUploader/php-s3-server#2]
Is it enough that `isValidRestRequest` simply verifies that the headers contain "host:" followed by the bucket name, or could this lead to requests being signed that shouldn't be allowed?

I suppose the AWS client should have limited permissions that only allow it to perform certain actions in specific buckets. If that's the case, and we're relying on those permissions for security, is there any need to validate the request before signing it?

**Comment by rnicholus** [comment]
> Is it enough that isValidRestRequest simply verifies that the headers contain "host:" followed by the bucket name

That depends entirely on your requirements. But there isn't much more to verify in the request itself.

> could this lead to requests being signed that shouldn't be allowed

Yes, absolutely.

> I suppose the AWS client should have limited permissions that only allow it to perform certain actions in specific buckets

This has been my approach. A set of keys specifically for use by Fine Uploader only with permissions appropriate for uploading files (and optionally deleting them, if this is a feature you want to support).

> we're relying on those permissions for security, is there any need to validate the request before signing it

Depends on the permissions, the sensitivity of the data, etc. I would suggest performing as much validation as reasonable/possible.

I'm happy to answer any more specific questions, if you have any.

**Comment by hubgit** [comment]
Thanks Ray - I think it's enough to know that we should set the IAM user's permissions as strictly as possible, and rely on those for security rather than request validation.

That does raise the question of why the signature is needed - there must be some circumstances in which the server would want to make sure only certain requests could be signed.

**Comment by rnicholus** [comment]
> That does raise the question of why the signature is needed

If you want to prevent a request from being sent, simply return an error status in your response. Additionally, if you return a JSON response of `{"invalid": true}`, Fine Uploader will not attempt to retry the request to your signature server.

**Comment by rnicholus** [comment]
Closing - let me know if there are any further questions/concerns.
