### ISSUE TITLE
Upload the related file to aws

### ISSUE THREAD

**Issue by dinesh-ranium** [FineUploader/php-s3-server#3]
You have not uploaded the aws class file. please add this file and credential class file also

**Comment by rnicholus** [comment]
What is an "aws class file"? And what is a "credential class file"?

**Comment by dinesh-ranium** [comment]
S3Client class file 
and 

Credentials class file

**Comment by rnicholus** [comment]
The S3Client must be downloaded by _you_ using composer. It's part of the AWS PHP SDK. See the composer file in the repo for details. As for the credentials, you must supply those.

**Comment by dinesh-ranium** [comment]
In  composer .json file 

why there is comment  invalid json

**Comment by rnicholus** [comment]
there is no comment in that file - it is valid JSON

**Comment by dinesh-ranium** [comment]
Sorry , not in the comment composer,son fil.

It comment on that file “Invaild Josn”.

You can also see just after your  name .
(click on that file).

And one more request . can you make this in laraval.
Thanks.

> On 03-Oct-2016, at 5:50 pm, Ray Nicholus <n.
>

**Comment by rnicholus** [comment]
no idea what you're talking about. sorry.
