### ISSUE TITLE
Unable to hanlde signature verification failure with S3 signature option

### ISSUE THREAD

**Issue by tmuks** [FineUploader/php-s3-server#4]
```
signature: {
            endpoint: "endpoint_ul"
        },
```

Cannot find a way to handle the failed signature verification, is there?
I tried with callback onError and onCancel none of them worked

Also signature verification returns failure it calls "objectProperties" and continues execution

**Comment by rnicholus** [comment]
You've posted a question for the JavaScript library in the php repo. Also, the issue tracker is for bugs and feature requests. Please read http://FineUploader.com/support.
