### ISSUE TITLE
Composer update block after package added

### ISSUE THREAD

**Issue by Roadirsh** [FineUploader/php-s3-server#6]
When I add fineuploader/php-s3-server": "1.1.0" to my composer.json file, the composer update stop working at "Resolving dependencies through SAT".
I ran composer update -vvv to get the more detailed output. 
The issue seems linked to this package.
Is it only me or is it more global ?

**Comment by rnicholus** [comment]
You'll need to talk to the composer team for this issue. Most likely an issue with your environment.
